export const NFT_TRAITS = [
  'Fur',
  'Background',
  'Ear',
  'Mouth Decoration',
  'Hat',
  'Neck',
  'Eyes',
  'Frame',
  'Mouth',
];

export const FARM_TRAITS: FarmData[] = [
  {
    name: 'A3C',
    traits: {
      Fur: ['pink', 'Coyote', 'Coqui'],
      Background: [
        'late night',
        'Happy Trees - JES Art',
        'Brickwall',
        'Consensus 2022 Uncommon',
        'Jackson Pollock',
        'Orange',
        'Stickers',
        'Neon',
        'Blue Grid',
      ],
      'Ear Decoration': ['Beauty Mark'],
      'Mouth Decoration': ['big moustache'],
      'Mouth decoration': ['big moustache'],
      Mouth: ['Rob Boss Beard'],
      Hat: [
        'crown',
        'Mardis Gras Hat',
        'Trash Can Lid',
        'Forest Camo',
        'TBLH Hat',
      ],
      Neck: ['blue collar', 'Vicar', 'The Fools Neck'],
      Glasses: ['visor dead', 'Fighter Pilot Glasses'],
      Frame: [
        'damien hirst',
        'Consensus 2022',
        'Dice',
        'Newspaper',
        'Fingerpaint',
        'Crypto Magazine',
      ],
      Eyes: ['Hoskytwo Eyes'],
    },
  },
  {
    name: 'BONE',
    traits: {
      Fur: ['baby blue', 'Scruff'],
      Background: [
        'poo',
        'This is Fine',
        'Ukraine',
        'Spamdle',
        'Busy',
        'Fluorescent Gradient',
        'Sunset Tones Gradient',
        'Livestream',
        'Obsidian',
      ],
      'Ear Decoration': ['Bandaged Ear Right'],
      'Mouth Decoration': ['tongue out'],
      'Mouth decoration': ['tongue out'],
      Hat: [
        'police',
        'holographic hat',
        'Blue Hat',
        'Beret',
        'Chef Hat',
        'Annie Hat',
        'Bloody Arrow',
      ],
      Neck: ['Faux Rug Survivor'],
      Glasses: ['cyber hosky', 'Sunset Glasses'],
      Eyes: ['Bloodyhell'],
      Frame: [
        'check mate',
        'Mega Pint',
        'FIRED!',
        'Hosky 2000 Computer',
        'Retro Coins',
        'Aboslutely',
      ],
      Mouth: ['hmmm'],
    },
  },
  {
    name: 'LIDO',
    traits: {
      Fur: ['white', 'turtle'],
      Background: [
        'red',
        'fireworks',
        'Pastel',
        'Salvador Hosky',
        'Bright Blue Green Gradient',
      ],
      'Mouth Decoration': ['sick', 'Bubblegum'],
      'Mouth decoration': ['sick', 'Bubblegum'],
      Hat: [
        'top hat red',
        'gold ribbon hat',
        'Pork Pie Hat',
        'Bicycle Helmet Orange',
      ],
      Glasses: ['visor heart', 'goggles'],
      Frame: [
        'fish bowl',
        'Traditional Painting',
        'Copper',
        'Cocktail',
        'Sticker',
        'Hosky Blocks',
        'Catastrophe',
      ],
      Mouth: ['sad', 'Zipped'],
      'Ear Decoration': ['Biggie Hair'],
      Eyes: [
        'Charles Eyes',
        'Grinch Eyes',
        'Were Eyes',
        'Ukraine Eyes',
        'Knitted Eyes',
        'Heterochromia',
      ],
    },
  },
  {
    name: 'CHEF',
    traits: {
      Fur: ['bear', 'Grey'],
      Background: [
        'blue',
        'Consensus 2022 Rare',
        'Black Radioactive Animated',
        'Underwater Animated',
        'Radioactive Yellow Animated',
        'Duplicate',
      ],
      'Mouth Decoration': ['pizza', 'Bubblegum Popped'],
      Hat: ['miner', 'Black Lunar New Year Hat', 'Yellow Feather Hat', 'Dune'],
      Glasses: ['gold glasses', 'Neistat'],
      Frame: [
        'Lunar New Year Gold',
        'Fools Gold',
        'Suits',
        'Joker',
        'Stamp',
        'Rug Me Daddy!',
        'Prison Bars',
        'NGMI',
      ],
      'Ear Decoration': ['Bandaged Ear Left'],
      Neck: ['Rug Pool Bowl'],
      Mouth: ['Banksy Mouth', 'Gherkin Mouth'],
      Eyes: ['White Eyes', 'Hoskasaur Eyes', 'Hoskrogu Eyes', 'Coyote Eyes'],
    },
  },
  {
    name: 'FARM',
    traits: {
      Fur: ['gold'],
      Background: [
        'khaki',
        'fireplace',
        'red gradient',
        'Iris',
        'green purple gradient',
        'granite',
        'cosmos',
      ],
      'Mouth Decoration': ['flaming hot'],
      'Mouth decoration': ['flaming hot'],
      Hat: [
        'robin hood',
        'martian',
        'karen',
        'buffon hat',
        'prisoner 42069',
        'afro',
        'rainbow hat',
        'lawyer wig',
      ],
      Neck: ['blue collar gold spikes'],
      Glasses: ['visor beam', 'pilot glasses tinted'],
      Frame: ['poo', 'food', 'zero'],
      'Ear Decoration': ['candle right'],
      Mouth: ['snowman', 'sausage', 'duckface', 'uncertain', "blingin'"],
      Eyes: ['black eye'],
    },
  },
  {
    name: 'FIKA',
    traits: {
      Fur: ['tiger fur', 'gold tiger', 'imagine dragons', 'panda', 'Clay Face'],
      Background: [
        'Yellow',
        'Landscape',
        'FIAT',
        'Slate',
        'Press Start',
        'Field Gradient',
      ],
      'Ear decoration': ['stud right'],
      Hat: [
        'trucker',
        'Bison',
        'Robin Hood Error',
        'Racing Helmet',
        'Black and White Jester',
        'Santa Hat Error',
        "Tea Cup World's Best Coder",
        'Black Mask',
        'Dumpling',
      ],
      Glasses: ['lennon', 'Asymmetrical Glasses'],
      Frame: ['astronaut', 'Vegas Computer', 'Another Holiday'],
      Mouth: ['sad-ish', 'Robot Mouth', 'Clown Mouth', 'Snarl'],
      'Mouth Decoration': ['Strawberry'],
      Neck: ['Trash Can'],
      Eyes: ['Beatenup'],
    },
  },
  {
    name: 'HERO',
    traits: {
      Fur: ['blue dog', 'Skull', 'NSFW'],
      Background: ['grey', 'Deep Green', 'Dimalix'],
      'Mouth Decoration': ['goatee'],
      Hat: ['hero', 'red woody hat', 'blue wooly hat', 'hero2', 'Cowboy Hero'],
      Neck: ['red collar gold spikes', 'bow tie'],
      Glasses: ['visor meh', 'Stitches', 'Hero Mask'],
      Frame: ['wood', 'Balloon', 'Jigsaw'],
      Mouth: ['LED Mouth', 'Dollar Mouth', 'Stitched Up'],
      'Ear Decoration': ['White Earphones'],
    },
  },
  {
    name: 'ITZA',
    traits: {
      Fur: ['Señor josquí', 'Flaming Hot', 'Hosky Sticker', 'Cerberosky'],
      Background: [
        'mint',
        'Full Moon',
        'Light Speed',
        'Gold Frameception',
        'Consensus 2022 Common',
        'GN',
        'Highly Classified',
        'GM',
      ],
      'Mouth Decoration': ['Burgundy Moustache'],
      'Ear decoration': ['double stud left'],
      Hat: [
        'viking',
        'elf hat',
        'King Tutankhamun',
        'Silver Crown Error',
        'Miner Error',
        'Flat Peak Error',
        'Elf Hat Error',
        'Bandana Error',
        'Viking Error',
        'Top Hat Blue Error',
        'Party Hat',
        'Head Wrap',
      ],
      Neck: ['Diamond Chain', 'Robot Bowtie', 'Green Poncho'],
      Glasses: [
        'laser visor',
        'Yellow Laser Error',
        'Green Laser Error',
        'Back To The Future Error',
        'Red Laser Error',
        'Blue Laser Error',
        'Visor Animated',
        'Pilot Glasses Classic',
      ],
      Frame: ['silver', 'Glass Jarsky', 'Wen'],
      Eyes: ['Knackered'],
    },
  },
  {
    name: 'JACK',
    traits: {
      Fur: ['oscar', 'Charles Mask', 'Glow In The Dark Skull'],
      Background: ['peach', 'Wernis', 'Epilogue', 'Pernis', 'Notepad'],
      'Mouth Decoration': ['Handlebar Moustache'],
      'Ear Decoration': ['right ring'],
      Hat: [
        'mcdonalds',
        'Sombrero',
        'Tea Cup',
        'Rob Boss',
        'McDonalds Error',
        'Captain Error',
        'Top Hat Red Error',
        'Crown Error',
        'Hero Error',
        'Poo Hat Error',
        'Hero 2 Error',
        'Gladiator Mask',
      ],
      Neck: [
        '2st Place Medal',
        '1rd Chain',
        'Poo Bowtie',
        'Blue Bowtie',
        'Bubblebath',
        'Trash Can',
      ],
      Glasses: [
        'blue laser',
        'Eyepatch Right Error',
        'Upside Down Error',
        'Eyepatch Left Error',
        '3D Gloss Error',
        'Retro Rainbow Eyes',
        'Eyes Patched Error',
        'Thug Life Error',
        'Dude Error',
        'Love Error',
      ],
      Frame: ['playing card', '!%*@#?', 'Crypto Ticker'],
    },
  },
  {
    name: 'PRIDE',
    traits: {
      Fur: ['doberman', 'led'],
      Background: ['cyan', 'Pop Art'],
      'Mouth Decoration': ['rainbow vomit'],
      'Ear Decoration': ['Candle Middle'],
      Hat: ['Black Lunar New Year Hat', 'Fez', 'Dank Hat'],
      Glasses: ['back to the future', 'Broken Pilot Glasses'],
      Frame: ['wernis', 'Felt', 'Sunlight'],
      Mouth: ['ooooo'],
      Neck: ['neckerchief'],
      Eyes: ['Overload', 'Flaming Hot Eyes', 'Cact-eyes'],
    },
  },
  {
    name: 'PSB',
    traits: {
      Fur: ['hoskasaur', 'Knitted', 'Crazy Mary'],
      Background: ['prison', 'Matrix', 'Blue Stepped Gradient'],
      'Mouth Decoration': ['Fighter Pilot Mask'],
      'Ear decoration': ['stud left'],
      Hat: [
        'Red Lunar New Year Hat',
        'HoskyMando',
        'Red Wooly Hat Error',
        'Squid Game Triangle',
        'Reindeer Error',
        'Horns',
      ],
      Neck: ['Blue Poncho'],
      Glasses: ['3d gloss'],
      Frame: ['Lunar New Year Wave', 'Thinking'],
      Mouth: ['happy'],
      Eyes: ['Pink Eye', 'Spicy Eyes'],
    },
  },
  {
    name: 'PSYA',
    traits: {
      Fur: ['yellow dog', 'Radioactive Orange', 'Family'],
      Background: [
        'red',
        'Black Radioactive',
        'Carbon Fiber',
        'Radioactive Yellow',
        'Blue Yellow Gradient',
      ],
      'Ear Decoration': ['Diamond Stud'],
      'Mouth Decoration': ['crumpet'],
      'Mouth decoration': ['crumpet'],
      Hat: [
        'spin top',
        'santa hat',
        'mcdonalds manager',
        'Purple Hat',
        'Fighter Pilot',
      ],
      Neck: ['Gold Bowtie'],
      Glasses: ['upside down'],
      Frame: ['frosty', 'Zeros Around the World', 'Banksy Tribute'],
      Eyes: ['Pink Eye', 'Hypno Eyes'],
    },
  },
  {
    name: 'QCPOL',
    traits: {
      Fur: ['hoskrogu', 'Frankenhosk'],
      Background: ['sunset', 'Morning Gradient'],
      'Ear Decoration': ['double stud right'],
      'Mouth Decoration': ['cigar'],
      Hat: [
        'captain',
        'Squid Game Square Error',
        'Squid Game Circle Error',
        'Squid Game Triangle Error',
        'Squid Game',
        'Third Ear Green',
        'Squid Game Error',
        'Pumpkin',
        'Pumpkin 2',
      ],
      Neck: ['red collar', 'chain'],
      Glasses: ['visor'],
      Frame: ['pernis', 'Think S#!tty'],
      Eyes: ['Crazy Eyes'],
    },
  },
  {
    name: 'SALT',
    traits: {
      Fur: ['hosky droid', 'Original OAP'],
      Background: ['purple', 'Orchid'],
      'Ear Decoration': ['double left rings'],
      'Mouth Decoration': ['Beard'],
      Hat: ['top hat blue', 'tiger hat', 'micky', 'YOLO Hat', 'Desert Camo'],
      Neck: ['Hosk Chain'],
      Glasses: ['3d glasses', 'Monocle'],
      Frame: ['candy cane', 'Out Of Ink'],
      Eyes: ['Crazy Eyes', 'Vegas Eyes', 'Coqui Eyes'],
    },
  },
  {
    name: 'SEA',
    traits: {
      Fur: [
        'holographic',
        'Red Tiger',
        'Hoskytwo',
        'Unknown',
        'Ghosky',
        'Cardoggo',
        'Vasil Mask',
        'War Paint',
      ],
      Background: [
        'navy',
        'Green Gradient',
        'Extra Stank',
        'Ganja',
        'Blue Purple Gradient',
        'Jes Art',
      ],
      'Ear Decoration': ['Double Bandaged Ears'],
      'Mouth Decoration': ['snorkel'],
      Hat: [
        'silver crown',
        'reindeer',
        'Hosk Cap',
        'Halo',
        'Neon Sphinx Hat',
        'Trent Barnes',
      ],
      Neck: ['eye patch right'],
      Frame: ['test card', 'Flies', 'Flies Animated'],
      Mouth: ['Knitted Mouth'],
      Glasses: ['red laser', 'eyepatch left', 'EyePatch Right', 'Tears'],
      Eyes: [
        'Dizzy Eyes',
        'Hypno Dizzy Eyes',
        'Brown Eyes',
        'Rolls Eyes',
        'Stoned Eyes',
      ],
    },
  },
  {
    name: 'VEGAS',
    traits: {
      Fur: [
        'radioactive pink',
        'Banksy',
        'Cardano Whale',
        'Werewolf',
        'Ghost Chain',
        'Vegas Mask',
      ],
      Background: [
        'baby blue',
        'Lunar New Year Blue',
        'Vegas',
        'Underwater',
        'April Fools',
        'Neon Pink Gradient',
        'Mint Gradient',
      ],
      'Mouth decoration': ['cigarette'],
      Hat: [
        'flat peak',
        'Micky Error',
        'Blood Poo Error',
        'McDonalds Manager Error',
        'HoskyFett',
        'Squid Game Circle',
        'Holographic Hat Error',
        'Squid Game Square',
        'King Tutankhamun Error',
        'The Fools Hat',
        'Splitting Headache',
        'HBI Hat',
      ],
      Neck: ['SlumDogeEx-Millionaire'],
      Glasses: ['green laser', 'Heads-Up Display', 'Late Night Glasses'],
      Frame: ['fairy lights', 'Ded'],
      Mouth: ['meh'],
      Eyes: [
        'Jake Eyes',
        'Vasil Eyes',
        'Neon Sphinx Eyes',
        'Hosky Island Eyes',
        'Psychedelic Eyes',
      ],
    },
  },
  {
    name: 'WOOF',
    traits: {
      Fur: ['joker', 'Original Retired'],
      Background: [
        'green',
        'snowfall',
        'beige',
        'Light Blue Gradient',
        'Hosky Blue Gradient',
        'FIN',
      ],
      'Ear Decoration': ['double right rings'],
      'Mouth Decoration': ['bone'],
      Hat: [
        'sweatband',
        'blood poo',
        'Sweatband 2',
        'Cork Hat',
        'Sphinx Hat',
        'FUD Cap',
        'Paper Bag',
      ],
      Glasses: ['thug life', 'Upside Down Right Way Up'],
      Frame: ['pernis vs wernis', 'Golden Shine'],
      Neck: ['hawaiian', 'Black Bowtie'],
      Eyes: [
        'Blue Eyes',
        'Cyclops Eyes',
        'White Glowing Eyes',
        'Clown Eyes',
        'Left or Right Eyes',
        'Scarred Eyes',
      ],
    },
  },
  {
    name: 'NANI',
    traits: {
      Fur: ['x-ray', 'ghost', 'radioactive green', 'grinch', 'fox'],
      Background: ['dark black', 'sahara'],
      'Mouth decoration': ['tooth'],
      Hat: [
        'poo hat',
        'Red Lunar New Year Hat',
        'We Need You',
        'Mohican',
        'Stay Palm',
        'Stay Palm Gold',
      ],
      Neck: ['Doggy Bowl'],
      Glasses: ['yellow laser', 'Wipers'],
      Frame: ['warning', 'Spinning Bowtie'],
      Mouth: ['wtf', 'snowman error'],
      Eyes: [
        'Overload',
        'Robot Eyes',
        'Glowing Eyes',
        'Twitchy Eyes',
        'Blinking',
      ],
    },
  },
  {
    name: 'POOL19',
    traits: {
      Fur: ['robot'],
      Background: ['space', 'fireworks lny'],
      'Mouth Decoration': ['eat poo'],
      'Mouth decoration': ['eat poo'],
      Hat: ['bandana'],
      Glasses: ['love'],
      Frame: ['green hazmat suit'],
      Mouth: ['yeh but no'],
    },
  },
  {
    name: 'POOL20',
    traits: {
      Fur: ['raccoon'],
      Background: ['deep purple', 'lny red'],
      'Ear Decoration': ['left ring'],
      'Ear decoration': ['left ring'],
      'Mouth Decoration': ['taco'],
      'Mouth decoration': ['taco'],
      Hat: ['dude'],
      Glasses: ['eyes patched'],
      Frame: ['orange hazmat suit'],
      Mouth: ['good boy'],
    },
  },
];

export type FarmData = {
  name: string;
  traits: FarmTrait;
};

export type FarmTrait = {
  Background?: string[];
  Fur?: string[];
  'Ear Decoration'?: string[];
  'Ear decoration'?: string[];
  'Mouth Decoration'?: string[];
  'Mouth decoration'?: string[];
  Hat?: string[];
  Neck?: string[];
  Eyes?: string[];
  Frame?: string[];
  Glasses?: string[];
  Mouth?: string[];
};
